---
- hosts: devvm
  tasks:
  - name: Install Double Commander
    apt:
      name: doublecmd-gtk
      state: latest
      install_recommends: no
    become: yes
  - name: Copy configuration files
    copy:
      src: "{{ playbook_dir }}/../config/doublecmd/"
      dest: "{{ ansible_env.HOME }}"
